SriAnugrahaSeva/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve as mediaserve

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$', mediaserve,
            {'document_root': settings.MEDIA_ROOT})
]

mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('register', views.registerView, name="register"),
    path('contact', views.contact, name="contact")
]

mainapp/forms.py
from django import forms
from django.forms import DateField, NumberInput
from .models import register

requirement_choices = [
    ('', 'Select Type'),
    ('type1', 'Type 1 - Planetary transit'),
    ('type2', 'Type 2 - House warming'),
    ('type3', 'Type 3 - Telugu Sampradaya'),
    ('type4', 'Type 4 - Homam'),
    ('type5', 'Type 5 - Sirartha'),
    ('type6', 'Type 6 - As per Telugu tradition')
]

services_choices = [
    ('', 'Select Services'),
]

mode_choices = [
    ('0', 'Select Mode'),
    ('1', 'Offline'),
    ('2', 'Online')
]

class registerForm(forms.Form):
    first_name = forms.CharField(label = "First Name")
    last_name = forms.CharField(label = "Last Name")
    email = forms.EmailField(label="Email ID")
    phonenumber = forms.CharField(label="Contact Number")
    address = forms.CharField(widget = forms.Textarea(
        attrs={'placeholder': 'Address'}
        )
    )
    postalCode = forms.IntegerField(label="Postal Code")
    requirement = forms.ChoiceField(choices=requirement_choices, label="Requirement")
    services = forms.ChoiceField(choices=services_choices, label="Package")
    mode = forms.ChoiceField(choices=mode_choices, label="Mode")
    date = forms.DateField(widget=NumberInput(attrs={'type': 'date'}))
    others = forms.CharField(required = False, widget = forms.Textarea(
        attrs={'placeholder': 'Any other details, Please type in the box'}
        )
    )

class contactForm(forms.Form):
    first_name = forms.CharField(label = "First Name")
    last_name = forms.CharField(label = "Last Name")
    subject = forms.CharField(label="Subject")
    message = forms.CharField(required = False, widget = forms.Textarea(
        attrs={'placeholder': 'Please type here...'}
        )
    )

templates/pages/contact.html
{% extends 'base.html' %}
{% block title %} Register | Sri Anugraha Seva {% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyle %}
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        @media (max-width:450px) {
            .margin_bottom {
                margin-bottom: 20px;
            }
        }
    </style>
{% endblock %}
{% block content %}
    {% include 'includes/header.html' %}
    <div class="container">
        <div class="row" style="margin-top: 40px;">
            <h3>Contact Us</h3>
            <div class="col-md-6 margin_bottom">
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                    </div>
                    {{ form.subject|as_crispy_field }}
                    {{ form.message|as_crispy_field }}
                    <button type="submit" class="btn btn-warning">Submit</button>
                </form>
            </div>
            <div class="col-md-6">
                <div id='map' style='overflow:hidden;height:520px; border-radius: 10px;'></div>
            </div>
        </div>
    </div>
    {% include 'includes/footer.html' %}
    {% block js %}
    <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoicmVhbHRvbmVzIiwiYSI6ImNrdG9ianRmbzBiOG0yb3BubnVkemhodGMifQ.KekNTV23BWlaXQ8B0xPWGg';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11'
        });
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [-0.1291203,51.5150899], // starting position
            zoom: 13 // starting zoom
        });
        // Set marker options.
        const marker = new mapboxgl.Marker({
            color: "#ff9818",
            draggable: true
        }).setLngLat([-0.1291203,51.5150899]).addTo(map);
        map.addControl(new mapboxgl.NavigationControl());
    </script>
    {% endblock %}
{% endblock %}

templates/pages/home.html
{% extends 'base.html' %}
{% block title %} Sri Anugraha Seva {% endblock %}
{% block extrastyle %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/slogan.css' %}" >
<style>
  .vanbanon {
    font-family: Arial;color: yellow;font-size:30px;background-color:transparent;text-align: center;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
  opacity: 1;
    font-weight: bold;
  }
  .vanban
  {
    font-family: Arial;color: white;font-size:30px;background-color:transparent;text-align: center;text-shadow: 1px 1px 2px black, 0 0 25px blue, 0 0 5px darkblue;
  opacity: 1;
    font-weight: bold;
  }
  .card-title {
    color:#000;
    text-transform: uppercase;
  }
  </style>
{% endblock %}
{% block content %}
  {% include 'includes/header.html' %}
  
  <div id="mainSlider" class="carousel slide" data-mdb-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="card bg-dark text-white">
          <img src="../../static/img/background.png" class="mainsliderimage d-block w-100" alt="mainSlider" />
          <div class="card-img-overlay" >
            <div class="row">
              <div class="col-md-4 h1_book text_book">
                <h1 class="card-text ">
                  Book for Vaideega
                  Karyas (Vedic Rituals) starting from Jatha Karma to 
                  Anthima Kriya
                </h1>
                <a href="{% url 'register' %}" class="btn btn-book" ><h6  style="margin-top: 4px;">Register Now</h6></a>
              </div>
              <div class="col-md-4 h6_book text_book">
                <h6 class="card-text h6_book_text">
                  Book for Vaideega
                  Karyas (Vedic Rituals) starting from Jatha Karma to 
                  Anthima Kriya
                </h6>
                <a href="{% url 'register' %}" class="btn btn-book" ><h6  style="margin-top: 4px;">Register Now</h6></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <section style="background-color: #f6f6f1;" id="about">
      <div class="container">
        <div class="row">

          <div class="col-md-6 aboutusimg">
            <img src="{% static 'img/bell.png' %}" class="bell_image"/>
          </div>

          <div class="col-md-6">
            <div class="card aboutustext">
              <div class="card-body">
                <h5 class="card-title">About Us</h5>
                <p class="card-text justify-content-center" style="text-align: justify; text-justify: inter-word;">
                  SRI ANUGRAHA SEVA is a new Hindu portal for 
                  Vaideega Seva. It provides all help to perform Vaideega
                  Karyas (Vedic Rituals) starting from Jatha Karma to 
                  Anthima Kriya. We are based in London.
                  We provide you the service in person with a priest or 
                  on line via Zoom or skype. We would cater to the 
                  needs of Hindus living in Western countries. Their 
                  needs are different from Hindus elsewhere. So we 
                  thought it is good to provide you all the basic Mantras, 
                  Pujas and other rituals in this website. 
                  Please note that we help you to perform Subham and 
                  Apara karyas as well.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="container servicescontainer" id="services">
      <h2 class="card-section-title">Services We Provide</h2>
      <div class="row row-services">
        <div class="col-md-4 card-margin">
          <div class="card">
            <img src="{% static 'img/s1.png' %}"  class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">Planetary transit</h5>
            </div>
          </div>
        </div>
        <div class="col-md-4 card-margin">
          <div class="card">
            <img src="{% static 'img/s2.png' %}" class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">House warming</h5>
            </div>
          </div>
        </div>
        <div class="col-md-4 card-margin">
          <div class="card">
            <img src="{% static 'img/s3.png' %}" class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">Telugu Sampradaya</h5>
            </div>
          </div>
        </div>
      </div>
      <div class="row row-services">
        <div class="col-md-4 card-margin">
          <div class="card">
            <img src="{% static 'img/s4.png' %}" class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">Homam</h5>
            </div>
          </div>
        </div>
        <div class="col-md-4 card-margin">
          <div class="card card-margin">
            <img src="{% static 'img/s5.png' %}" class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">Sirartha</h5>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card card-margin">
            <img src="{% static 'img/s6.png' %}" class="card-img-top card_img"/>
            <div class="card-body">
              <h5 class="card-title">As per Telugu tradition</h5>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% include 'includes/footer.html' %}
  {% block js %}
  {% load static %}
<script>
  const audioControButton = document.querySelectorAll(".play__pause");

function playPauseAudio(btn, track) {
  if (track.paused) {
    track.play();
    btn.classList.add("pause");
    btn.classList.remove("play");
  } else {
    track.pause();
    btn.classList.add("play");
    btn.classList.remove("pause");
  }
}

// Loop all instance of play buttons
if (audioControButton.length > 0) {
  audioControButton.forEach((playButton) => {
    playButton.addEventListener("click", (e) => {
      e.preventDefault;
      let elemContainer = playButton.parentElement;
      let track = elemContainer.querySelector("audio");
      stopAllAudio(track);
      playPauseAudio(playButton, track);
    });
  });
}

function stopAllAudio(elem) {
  const audios = document.getElementsByTagName("audio");
  for (var i = 0, len = audios.length; i < len; i++) {
    if (audios[i] != elem) {
      audios[i].pause();
      console.log(audios[i].nextElementSibling);
      audios[i].nextElementSibling.classList.remove("pause");
      audios[i].nextElementSibling.classList.add("play");
    }
  }
}

</script>
 <script>
  var audio = document.querySelector('audio');
  var span1 = document.querySelector('div#vanban1');
  var span2 = document.querySelector('div#vanban2');
  var track = audio.textTracks[0];
  track.mode = 'hidden';
  var idx = 0;
  track.oncuechange = function(e) {
    var cue = this.activeCues[0];
    if (cue) {
        if (idx == 0) {
      span2.className = 'vanban';
            span1.innerHTML = '';
            span1.className = 'vanbanon';
            span1.appendChild(cue.getCueAsHTML());
        } else {
            span1.className = 'vanban';
            span2.innerHTML = '';
            span2.className = 'vanbanon';
           span2.appendChild(cue.getCueAsHTML());
        }
        }
        idx = ++idx % 2;
  };
  </script>
  {% endblock %}
{% endblock %}

templates/pages/register.html
{% extends 'base.html' %}
{% block title %} Register | Sri Anugraha Seva {% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
{% endblock %}
{% block content %}
    {% include 'includes/header.html' %}
    <div class="register_body container">
        <h4>Register</h4>
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.phonenumber|as_crispy_field }}
                </div>
            </div>
            {{form.address|as_crispy_field}}
            <div class="row">
                <div class="col-md-6">
                    {{ form.postalCode|as_crispy_field }}
                </div>
                
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form.requirement|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.services|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.mode|as_crispy_field  }}
                </div>
            </div>
            {{ form.date|as_crispy_field }}
            {{ form.others|as_crispy_field }}
            <button type="submit" class="btn btn-warning">Submit</button>
        </form>
        {% if messages %}
        <ul class="messages alert-success">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
{% endif %}
    </div>
    {% include 'includes/footer.html' %}
    {% block js %}
    <script language="javascript" type="text/javascript">  
        $(document).ready(function() {
            //create arrays to store option and values
            var type1 = [
                {display: "Vastu Puja", value: "Vastu Puja" },    
                {display: "Milk fever", value: "Milk fever" },
                {display: "Ganapati Puja", value: "Ganapati Puja" },
                {display: "Punyahavasanam", value: "Punyahavasanam" },
                {display: "Ganapati Homam", value: "Ganapati Homam" },
                {display: "Navagraha homam", value: "Navagraha homam" },
                {display: "Lakshmi Homam", value: "Lakshmi Homam" }
            ];
               
            var type2 = [
                {display: "Vastu Puja", value: "Vastu Puja" },
                {display: "All Dwara Pooja", value: "All Dwara Pooja" },
                {display: "Agni Puja", value: "Agni Puja" },
                {display: "Milk fever", value: "Milk fever" },
                {display: "Lakshmi Ganapati Homam", value: "Lakshmi Ganapati Homam" },
                {display: "Satyanarayana Puja Lakshmi", value: "Satyanarayana Puja Lakshmi" },
                {display: "Saffron consecration", value: "Saffron consecration" }
            ];
            
            var type3 = [
                {display: "Satyanarayana Puja", value: "Satyanarayana Puja" },
                {display: "Navagraha Puja", value: "Navagraha Puja" },
                {display: "Loka Balakar Puja", value: "Loka Balakar Puja" },
                {display: "Hall worship", value: "Hall worship" },
                {display: "Lakshmi Kunguma Archana", value: "Lakshmi Kunguma Archana" },
            ];

            var type4 = [
                {display: "Ganapati Homam", value: "Ganapati Homam" },
                {display: "Mrutyunjaya Homam", value: "Mrutyunjaya Homam" },
                {display: "Sudarshana Homam", value: "Sudarshana Homam" },
                {display: "Navagraha homam", value: "Navagraha homam" },
                {display: "Lakshmi Homam", value: "Lakshmi Homam" },
                {display: "Ayushya Homam", value: "Ayushya Homam" },
                {display: "Chandi Homam", value: "Chandi Homam" },
                {display: "Vastu Puja", value: "Vastu Puja" },
                {display: "Vastu Homam", value: "Vastu Homam" },
                {display: "Dhanvantri Homam", value: "Dhanvantri Homam" },
                {display: "Ashtalakshmi Homam", value: "Ashtalakshmi Homam" },
                {display: "Durga Homam", value: "Durga Homam" }
            ]

            var type5 = [
                {display: "Parvana Vidhana Sirartha", value: "Parvana Vidhana Sirartha" },
                {display: "Hiranya Sirartham", value: "Hiranya Sirartham" },
                {display: "No Moon Day", value: "No Moon Day" }
            ];

            var type6 = [
                {display: "Tatnam (Sirartham)", value: "Tatnam (Sirartham)" },
                {display: "Bindapradhanam Darpanam", value: "Bindapradhanam Darpanam" }
            ];
            
            //If parent option is changed
            $("#id_requirement").change(function() {
                var parent = $(this).val();
                switch(parent){
                    case 'type1':
                        $('#id_services').attr('disabled', false);
                        list(type1);
                        break;
                    case 'type2':
                        $('#id_services').attr('disabled', false);
                        list(type2);
                        break;
                    case 'type3':
                        $('#id_services').attr('disabled', false);
                        list(type3);
                        break;
                    case 'type4':
                        $('#id_services').attr('disabled', false);
                        list(type4);
                        break;
                    case 'type5':
                        $('#id_services').attr('disabled', false);
                        list(type5);
                        break;
                    case 'type6':
                        $('#id_services').attr('disabled', false);
                        list(type6);
                        break;
                    default: //default child option is blank
                        $("#id_services").html('');
                        $('#id_services').attr("disabled", true);
                        break;
                }
            });
    
            function list(array_list) {
                $("#id_services").html("");
                $(array_list).each(function (i) {
                    $("#id_services").append("<option value='" + array_list[i].value + "'>" + array_list[i].display + "</option>");
                });
            }
        });
        </script>
    {% endblock %}
{% endblock %}